#!/bin/bash
sudo su -c 'curl https://raw.githubusercontent.com/michaldaniel/elementary-script/master/resources/numix-circle.index.theme > /usr/share/icons/Numix-Circle/index.theme'
sudo su -c 'curl https://raw.githubusercontent.com/michaldaniel/elementary-script/master/resources/elementay-plus.index.theme > /usr/share/icons/elementaryPlus/index.theme'
sudo su -c 'curl https://raw.githubusercontent.com/michaldaniel/elementary-script/master/resources/ultra-flat.index.theme > /usr/share/icons/Ultra-Flat/index.theme'
sudo su -c 'rm /usr/share/icons/Ultra-Flat/devices/scalable/system.svg'
sudo su -c 'rm /usr/share/icons/Ultra-Flat/places/scalable/mail*'
sudo su -c 'rm /usr/share/icons/Ultra-Flat/places/scalable/stock_i*'
sudo su -c 'rm /usr/share/icons/Ultra-Flat/places/scalable/stock_o*'
sudo su -c 'rm /usr/share/icons/Ultra-Flat/places/scalable/stock_s*'
